CREATE TABLE users (
    email VARCHAR(255) PRIMARY KEY NOT NULL,
    username VARCHAR(100)  NOT NULL,
    point INT DEFAULT 0,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
